/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class socket_Protocols */

#ifndef _Included_socket_Protocols
#define _Included_socket_Protocols
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     socket_Protocols
 * Method:    raw
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Protocols_raw
  (JNIEnv *, jobject);

/*
 * Class:     socket_Protocols
 * Method:    udp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Protocols_udp
  (JNIEnv *, jobject);

/*
 * Class:     socket_Protocols
 * Method:    tcp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Protocols_tcp
  (JNIEnv *, jobject);

/*
 * Class:     socket_Protocols
 * Method:    icmp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Protocols_icmp
  (JNIEnv *, jobject);

/*
 * Class:     socket_Protocols
 * Method:    eth_p_all
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Protocols_eth_1p_1all
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
