/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class socket_Interfaces */

#ifndef _Included_socket_Interfaces
#define _Included_socket_Interfaces
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     socket_Interfaces
 * Method:    inaddr_any
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_socket_Interfaces_inaddr_1any
  (JNIEnv *, jobject);

/*
 * Class:     socket_Interfaces
 * Method:    inaddr_loopback
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_socket_Interfaces_inaddr_1loopback
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
