/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class socket_Options */

#ifndef _Included_socket_Options
#define _Included_socket_Options
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     socket_Options
 * Method:    so_debug
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_so_1debug
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    so_broadcast
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_so_1broadcast
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    so_reuseaddr
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_so_1reuseaddr
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    so_keepalive
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_so_1keepalive
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    so_linger
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_so_1linger
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    so_oobinline
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_so_1oobinline
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    so_sndbuf
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_so_1sndbuf
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    so_recvbuf
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_so_1recvbuf
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    so_dontroute
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_so_1dontroute
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    so_rcvlowat
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_so_1rcvlowat
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    so_rcvtimeo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_so_1rcvtimeo
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    so_sndlowat
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_so_1sndlowat
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    so_sndtimeo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_so_1sndtimeo
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    ip_add_membership
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_ip_1add_1membership
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    ip_block_source
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_ip_1block_1source
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    ip_drop_membership
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_ip_1drop_1membership
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    ip_drop_source_membership
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_ip_1drop_1source_1membership
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    ip_multicast_if
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_ip_1multicast_1if
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    ip_multicast_loop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_ip_1multicast_1loop
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    ip_multicast_ttl
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_ip_1multicast_1ttl
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    ip_unblock_source
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_ip_1unblock_1source
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    mcast_block_source
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_mcast_1block_1source
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    mcast_join_group
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_mcast_1join_1group
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    mcast_join_source_group
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_mcast_1join_1source_1group
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    mcast_leave_group
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_mcast_1leave_1group
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    mcast_leave_source_group
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_mcast_1leave_1source_1group
  (JNIEnv *, jobject);

/*
 * Class:     socket_Options
 * Method:    mcast_unblock_source
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Options_mcast_1unblock_1source
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
