/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class socket_Domains */

#ifndef _Included_socket_Domains
#define _Included_socket_Domains
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     socket_Domains
 * Method:    af_inet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Domains_af_1inet
  (JNIEnv *, jobject);

/*
 * Class:     socket_Domains
 * Method:    pf_packet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Domains_pf_1packet
  (JNIEnv *, jobject);

/*
 * Class:     socket_Domains
 * Method:    af_packet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Domains_af_1packet
  (JNIEnv *, jobject);

/*
 * Class:     socket_Domains
 * Method:    af_unix
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Domains_af_1unix
  (JNIEnv *, jobject);

/*
 * Class:     socket_Domains
 * Method:    af_unspec
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Domains_af_1unspec
  (JNIEnv *, jobject);

/*
 * Class:     socket_Domains
 * Method:    af_file
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Domains_af_1file
  (JNIEnv *, jobject);

/*
 * Class:     socket_Domains
 * Method:    af_inet6
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Domains_af_1inet6
  (JNIEnv *, jobject);

/*
 * Class:     socket_Domains
 * Method:    pf_inet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Domains_pf_1inet
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
