/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class socket_Types */

#ifndef _Included_socket_Types
#define _Included_socket_Types
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     socket_Types
 * Method:    sock_stream
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Types_sock_1stream
  (JNIEnv *, jobject);

/*
 * Class:     socket_Types
 * Method:    sock_raw
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Types_sock_1raw
  (JNIEnv *, jobject);

/*
 * Class:     socket_Types
 * Method:    sock_dgram
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_socket_Types_sock_1dgram
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
